platform :ios, '11.0'
flutter_application_path = 'flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'flutter_ios' do
  
  use_frameworks!
  install_all_flutter_pods(flutter_application_path)

  pod 'AFNetworking'
  pod 'Masonry'
  pod 'ReactiveObjC'
end

# 新增的配置
post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end


